export const counterList = [
  {
    region: "منطقه 1خراسان ",
    provinceName: "خراسان رضوی ",
    cityName: "مشهد ",
    counterCode: "245151",
    counterName: "پایانه باهنر مشهد",
  },
  {
    region: "منطقه 1خراسان ",
    provinceName: "خراسان جنوبی ",
    cityName: "بیرجند ",
    counterCode: "245278",
    counterName: "بازار مرکزی بیرجند ",
  },
  {
    region: "منطقه 1خراسان ",
    provinceName: "کرمان ",
    cityName: "جیرفت ",
    counterCode: "245435",
    counterName: "بلوار شهدا",
  },
  {
    region: "منطقه 2 اذربایجان",
    provinceName: "آذربایجان شرقی ",
    cityName: "تبریز",
    counterCode: "245103",
    counterName: "زعفرانیه ",
  },
  {
    region: "منطقه 2 اذربایجان",
    provinceName: "آذربایجان غربی ",
    cityName: "ارومیه",
    counterCode: "245122",
    counterName: "پناهگاه ",
  },
  {
    region: "منطقه 3 اصفهان",
    provinceName: "اصفهان",
    cityName: "اصفهان ",
    counterCode: "245175",
    counterName: "میدان ولیعصر بهارستان ",
  },
  {
    region: "منطقه 4 فارس",
    provinceName: "فارس",
    cityName: "شیراز",
    counterCode: "245468",
    counterName: "فرصت شیراز",
  },
  {
    region: "منطقه 4 فارس",
    provinceName: "فارس",
    cityName: "شیراز",
    counterCode: "245112",
    counterName: "بلوار پاسداران",
  },
  {
    region: "منطقه 5 البرز",
    provinceName: "البرز",
    cityName: "کرج ",
    counterCode: "245320",
    counterName: "45 متری گلشهر",
  },
  {
    region: "منطقه 5 البرز",
    provinceName: "البرز",
    cityName: "کرج ",
    counterCode: "245329",
    counterName: "مترو کرج ",
  },
  {
    region: "منطقه 6 قم",
    provinceName: "قم",
    cityName: "قم",
    counterCode: "245390",
    counterName: "شهرداری منطقه 2 ",
  },
  {
    region: "منطقه 7 قزوین",
    provinceName: "قزوین",
    cityName: "قزوین ",
    counterCode: "245113",
    counterName: " میدان عارف",
  },
  {
    region: "منطقه 7 قزوین",
    provinceName: "گیلان ",
    cityName: "رشت",
    counterCode: "245167",
    counterName: "سبزه میدان",
  },
  {
    region: "منطقه 7 قزوین",
    provinceName: "کردستان ",
    cityName: "سنندج",
    counterCode: "245123",
    counterName: "بوستان شادی",
  },
  {
    region: "منطقه 7 قزوین",
    provinceName: "همدان ",
    cityName: "همدان ",
    counterCode: "245305",
    counterName: "میدان سپاه ",
  },
  {
    region: "منطقه 9 تهران",
    provinceName: "تهران ",
    cityName: "تهران ",
    counterCode: "245232",
    counterName: "میدان فردوسی",
  },
  {
    region: "منطقه 10 تهران",
    provinceName: "تهران ",
    cityName: "تهران ",
    counterCode: "245487",
    counterName: "صالح آباد ",
  },
  {
    region: "منطقه 10 تهران",
    provinceName: "تهران ",
    cityName: "تهران ",
    counterCode: "245271",
    counterName: "میدان آزادی",
  },
  {
    region: "منطقه 11 خوزستان",
    provinceName: "خوزستان ",
    cityName: "اهواز",
    counterCode: "245343",
    counterName: "کوروش اهواز",
  },
  {
    region: "حوزه شمال ",
    provinceName: "مازندران ",
    cityName: "ساری",
    counterCode: "245134",
    counterName: " بلوار آزادی",
  },
];
